sudo: required
language: node_js
node_js:
- '12'
cache:
  directories:
  - "./node_modules"
  - "$HOME/google-cloud-sdk/"
jobs:
  include:
  - stage: Install modules
    script: npm install;
  - stage: Build app
    script: ng serve -o;
    after_success:
      - npm install -g firebase-tools
      - firebase deploy --token "$FIREBASE_TOKEN"
