sudo: required
language: node_js
node_js:
- '12'
cache:
  directories:
  - "./node_modules"
  - "$HOME/google-cloud-sdk/"
jobs:
  include:
  - stage: Build app
    script: ng build;
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN